inherit_from: .rubocop_todo.yml

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/policies/movie_policy.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'