development:
  tmdb_key: 59cdee07cbe670ca1fa42f87e50a3ad9
test:
  tmdb_key: 59cdee07cbe670ca1fa42f87e50a3ad9
staging:
  tmdb_key: 59cdee07cbe670ca1fa42f87e50a3ad9
production:
  tmdb_key: <%= ENV["tmdb_key"] %>